### PR TITLE
Data save/load speed of qcodes sqlite backend vs hdf5 and numpy

### PR DESCRIPTION
**Pull request by astafan8**
This report measures data saving and loading times for QCoDeS SQLite backend, HDF5 file backend, and numpy npy file backend. The latter backends are implemented in the notebook. 

The data that the backends are being tested on is generated. The shape of the data is adjustable to some extent, but still this data represents a somewhat particular experiment.

The report is in the form of a jupyter notebook, sorry that it's not rst.

All comments are welcome.

### CODE REVIEW

**Comment by astafan8** [comment]
@wpfff confirmed that HDF5 in the way it is used in the notebook is a good reference.

**Comment by Dominik-Vogel** [comment]
You are saying that HDF5 is not widely used. I think it is the most common way of storing binary scientific data... (basically all matlab files.)

**Comment by astafan8** [comment]
oh, it's just bad english, i'll fix it :) they are both widely used and are efficient

**Review by WilliamHPNielsen — APPROVED** [review]
LeGiTiMately Looks Good To Me.

**Pull request merged**
